name: AiPacketClassifier
channels:
  - defaults
  - pytorch-nightly
  - nvidia
dependencies:
  - python=3.9.5
  - scapy=2.4.3
  - transformers=4.29.2
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1